### ISSUE TITLE
Add support for MINGW-UCRT packages

### ISSUE THREAD

**Issue by larskanis** [ruby/setup-ruby-pkgs#15]
Currently the packages that are installed are `mingw-w64-i686` or `mingw-w64-x86_64` depending on the `RUBY_PLATFORM`: https://github.com/MSP-Greg/setup-ruby-pkgs/blob/331fdbfba8231bbc43d22716c6e773162af807d2/mingw.js#L201

However with the upcoming release of RubyInstaller-3.1 the package prefix has to be `mingw-w64-ucrt-x86_64` instead.

Note: The `ridk exec` or `ridk enable` commands respect the different MINGW PATH and MINGW package prefix on UCRT already. So if `ridk` is used everything works already: https://github.com/oneclick/rubyinstaller2/blob/4300b3dbf4c2d9bae1522188ecccf7294b2e7617/lib/ruby_installer/build/msys2_installation.rb#L23-L35

**Comment by MSP-Greg** [comment]
Lars,

Code for this has been added to the 'v1' branches of both this repo and ruby/setup-ruby, so it should detect what package to install across Ruby <= 3.0, 3.1, head, mingw, & ucrt.
