### ISSUE TITLE
Getting `ETIMEDOUT` fairly often

### ISSUE THREAD

**Issue by ianks** [ruby/setup-ruby-pkgs#26]
Noticing that I'm getting some `ETIMEDOUT` errors fairly regularly ([here's one example](https://github.com/oxidize-rb/rb-sys/actions/runs/3406642354/jobs/5665492441)). Figured I'd report in case anyone else is experiencing something similar.

**Comment by dentarg** [comment]
Report to GitHub? Can't see that this action is doing anything wrong, maybe it could have retries built-in.

```
$ host 185.199.108.133
133.108.199.185.in-addr.arpa domain name pointer cdn-185-199-108-133.github.com.
```

**Comment by MSP-Greg** [comment]
This Action uses the code from setup-ruby.  When the log shows the following, it's running code from it:
```
——————————————————    Ruby tasks using: ruby/setup-ruby/v1
```

I've seen the error with setup-ruby.  I run some code locally that uses both GitHub API's (v3 and v4).  No connection with GitHub Actions (or setup-ruby).  I built retries into it, and sometimes it fails with 4 retries.  So, I think it's something with the GitHub/MSFT cloud?

**Comment by MSP-Greg** [comment]
Both setup-ruby and this repo have been updated.  Let's see if this fixes the `ETIMEDOUT` issues.
