### ISSUE TITLE
Timeouts when installing packages through pacman

### ISSUE THREAD

**Issue by deivid-rodriguez** [ruby/setup-ruby-pkgs#28]
I've been seeing this kind of failure recently: https://github.com/rubygems/rubygems/actions/runs/3863586315/jobs/6585862294.

I google the error message and I think we could benefit from using the `--disable-download-timeout` option as recommended here: https://github.com/msys2/MSYS2-packages/issues/1658#issuecomment-495955432. It has a lot of 👍 :)

I can send a PR.

**Comment by MSP-Greg** [comment]
@deivid-rodriguez Thanks.  I've also seen that, but you may have noticed similar issues with GitHub Actions in general.  My favorite is when one clicks open an Actions log step, and it shows a red error or something...

Regardless, PR ok, or I can do it.  Not sure if you've got yarn, etc installed...

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

Released as 1.32.4

JFYI, I can one job run for quite a while, adding a timeout to the 'setup-ruby-pkgs' step may be a good idea.

**Comment by deivid-rodriguez** [comment]
Thanks!
